apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gonenote.fullname" . }}
  labels: {{- include "gonenote.labels" . | nindent 4 }}
data:
  REDIS_URL: redis://{{ include "gonenote.redis.fullname" . }}:{{ .Values.redis.port | toString }}
  MAX_NOTE_LENGTH: {{ .Values.app.maxNoteLength | quote }}
  DEFAULT_TTL: {{ .Values.app.defaultTtl | quote }}
