apiVersion: v1
kind: Service
metadata:
  name: {{ include "gonenote.fullname" . }}
  labels: {{- include "gonenote.labels" . | nindent 4 }}
spec:
  selector: {{- include "gonenote.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gonenote.fullname" . }}
  labels: {{- include "gonenote.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "gonenote.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "gonenote.labels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ include "gonenote.fullname" . }}
            - secretRef:
                {{- if .Values.useExistingSecret }}
                name: {{ .Values.existingSecret.name }}
                {{- else }}
                name: {{ include "gonenote.fullname" . }}
                {{- end }}
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: {{ .Values.app.port | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 15
            timeoutSeconds: 5
