{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gonenote.fullname" . }}
  labels: {{- include "gonenote.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "A valid .Values.secretKey is required (generate: openssl rand -hex 32)" .Values.secretKey | quote }}
{{- end }}
